name: API Test with Newman

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Run Application
        run: ./gradlew bootRun

      - name: Wait for Application to Start
        run: |
          echo "Waiting for Spring Boot application to start..."
          sleep 20

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Newman & Html Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Newman Tests
        run: newman run ./postman/collection.json -r html --reporter-html-export ./postman/report.html

      - name: Archive Newman Test Results
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-results
          path: ./postman/report.html